[package]
name = "proj1"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.0-rc.0"

[profile.release]
opt-level = 3               # Use slightly better optimizations.
overflow-checks = false     # Disable integer overflow checks.
